### ISSUE TITLE
Problem with dialysis codelist

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#1008]
This codelist is triggering a server 500 error

https://www.opencodelists.org/codelist/opensafely/dialysis/2020-07-16/

**Comment by brianmackenna** [comment]
In the interim the codelist can be got by going to the url https://www.opencodelists.org/codelist/primis-covid19-vacc-uptake/?q=kidney @alexwalkerepi @acagreen17

**Comment by alexwalkerepi** [comment]
If that download link is working then it should work to pull them into the repo with the normal `codelists update` tool. I think it's just being able to view it on the site that's not working.

**Comment by brianmackenna** [comment]
@inglesp has made a new version at

https://www.opencodelists.org/codelist/opensafely/dialysis/3ce108ac/

**Comment by rebkwok** [comment]
Closing - resolved with new version
