### ISSUE TITLE
NHSD Haematological cancers SNOMED list

### ISSUE THREAD

**Issue by rose-higgins** [opensafely-core/opencodelists#1074]
There are several SNOMED codes present in the Haematological Cancers codelist, (present in ID 1 [here](https://digital.nhs.uk/dashboards/gp-covid-19-vaccine-dashboard/3rd-primary-dose-cohort-identification-specification))

SNOMED codes with error/issues in national published codeset

1. Angioimmunoblastic T-cell lymphoma with dysproteinaemia code - 1090241000000100 (in national codeset). This code does not exist in the SNOMED browser. However the code with that description is '1090241000000107'. This has been updated in our codelist.

2. B-cell non-Hodgkin's lymphoma - 1091921000000100 (in national codeset). This code doesn't exist in SNOMED browser. The code with that description is '1091921000000103'. This has been updated in our codelist.

3. B-cell Hodgkin's lymphoma - 1091891000000100 (in national codeset). This code doesn't exist in SNOMED browser. The code with that description is '1091891000000106'. This has been updated in our codelist.

@brianmackenna  to note these are issues with the other set of look ups we are using, based on the shielded patients list. @acagreen17 to note as well.

**Comment by rose-higgins** [comment]
It downloads as an excel file (not csv or txt), so not sure if that is possible...

**Comment by inglesp** [comment]
The bad codes are baked into the Excel file, so there's nothing we can do about it.

Note that they're also on the [NHS Data Model and Dictionary](https://datadictionary.nhs.uk/index.html) webpage.

**Comment by rose-higgins** [comment]
An unrelated issue reported by NHSD relating to this codelist is reported in #1079. This error isn't present in our version of the codelist.

**Comment by rebkwok** [comment]
@rose-higgins Is there anything more to address in this issue?
