### ISSUE TITLE
NHSD Haematological cancers SNOMED known issue: chronic lymphocytic leukaemia

### ISSUE THREAD

**Issue by rose-higgins** [opensafely-core/opencodelists#1079]
The shielded patient list for Haematological malignancies published [here ](https://digital.nhs.uk/dashboards/gp-covid-19-vaccine-dashboard/3rd-primary-dose-cohort-identification-specification)(under rule 1) by NHSD had a known issue. This issue is recorded [here ](https://digital.nhs.uk/coronavirus/treatments#known-issues)and was recorded as fixed on 29th January 2022.  

The known issue is the omission of 92814006 Chronic lymphocytic leukaemia (CLL), disease (disorder) SNOMED code. This error was estimated to have impacted 27,371 potential shielded patients.

The haematological cancers SNOMED [codelist](https://www.opencodelists.org/codelist/nhsd/haematological-malignancies-snomed/31a49191/) in OpenCodelists produced from that look up has been checked against this error, and **does contain the relevant SNOMED code**. No other actions need to be taken. 

Other issues in this codelist, documented in #1074 are not relating to this known issue.

**Comment by rose-higgins** [comment]
FYI @brianmackenna the code in the published issue is present in our codelist. If you are happy we could close this issue I think.

**Comment by brianmackenna** [comment]
Just before we close. The NHSD issue states 

> 27,371 potentially eligible patients have been identified as being impacted.

This doesn't match the figures we have identified however it isn't clear to me what "potentially eligible" means. has this definition come up elsewhere?

**Comment by rose-higgins** [comment]
I haven't been able to find anything referring to this definition else where on the site other than [here](https://digital.nhs.uk/coronavirus/treatments/methodology/datasets-used)(in screenshot below)
![image](https://user-images.githubusercontent.com/95700645/154672025-7a6a4cc4-1b34-4a1c-b8c6-730a2b98dfe5.png)
 
Also I haven't been able to find any prevalence numbers for CLL or nothing published which sheds light on how those numbers are arrived at.

**Comment by rebkwok** [comment]
@rose-higgins Can this issue be closed now?
