### ISSUE TITLE
Codelists with no published versions show up in search

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#1111]
For instance, [Monoamine Oxidase Inhibitors DM&D](https://www.opencodelists.org/codelist/opensafely/monoamine-oxidase-inhibitors-dmd/) shows up in a [search for "antidepressants"](https://www.opencodelists.org/?q=antidepressants), but is not accessible to anybody outside the opensafely organisation.

Implementation notes for @lucyb:

* [Here's a failing test case](https://gist.github.com/inglesp/c6bf4efc1bd6c2b9b43b0b8ee959c5ed)
* The relevant part of the [data model](https://github.com/opensafely-core/opencodelists/blob/main/codelists/models.py) is:
    * A `Codelist` has one or more `Version`s
    * A `Version` has a status which can be "published", "under review", or "draft"
    * A `Codelist` has one or more `Handle`s, which link a `Codelist` to a `User` or `Organisation`
* Searches are handled by [this view function](https://github.com/opensafely-core/opencodelists/blob/e93142091131443e96b1271f07dacb6143e55457/codelists/views/index.py#L9-L32).
* You probably want to filter `codelists`, defined on [line 30](https://github.com/opensafely-core/opencodelists/blob/e93142091131443e96b1271f07dacb6143e55457/codelists/views/index.py#L30) to remove any codelists with no published versions

**Comment by lucyb** [comment]
Fix has been deployed. "Monoamine Oxidase Inhibitors DM&D" is no longer visible in the search results (and neither are other codelists without a published version).

Can this issue be closed?

**Comment by inglesp** [comment]
> Can this issue be closed?

Yes!
