### ISSUE TITLE
Surfacing inconsistent column numbers in uploaded codelists error

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely-core/opencodelists#1121]
I had an issue where a user was trying to upload a CSV with snomed codes and categories. This resulted in an error that could have been clearer that occurred on the upload page. 

```
Incorrect number of columns
```

Suggest change: `The CSV has N headers, but row X contains M columns`

**Comment by rebkwok** [comment]
Closing as the main upload form checks for inconsistent numbers of columns in rows, and #1459 will make the old-style form check it too.
