### ISSUE TITLE
User can't view published codelist if they have a version in draft

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1127]
The default view for a codelist returns the latest visible version for that user.  If the user has a version that's in draft, that is returned as the latest visible version, in the builder view.  However, as there are no links to other versions on the builder view, a user with a new draft version has no way to see the current published version (without logging out and searching for it, and then it'll only be visible if it's an OpenSAFELY-owned codelist).

I think there are two possible solutions:
1) Continue to return the lastest draft version for the user as the default, if there is one, but add links to other versions on the builder page
2) Make the default version returned for a codelist the latest published version (which will contain links to drafts/reviews if the user has any); only return draft or review versions if there is no published one

On the users "My codelists" page, we list their published codelists and codelists in draft.  If there's both a published and draft version of the same codelist for a user, it appears in both sections.  The urls for published codelists are `/codelist/<owner>/<codelist_id>` and for drafts `codelists/<owner>/<codelist_id>/<version_id>` but currently they'll take you to the same builder page for the draft.

**Comment by inglesp** [comment]
I think we should definitely add links to the other versions on the builder page.

I suppose if a codelist appears multiple times on the "My codelists" page, you should be taken to the most relevant version.
