### ISSUE TITLE
Prevent/restrict owner changes on published codelists?

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1128]
Metadata can be updated for codelists that are either under review or published.  This includes changing the owner of a codelist, which could potentially cause problems when a codelist is owned by an organisation. 

E.g.
1) User1 creates and publishes a codelist "foo" under the OpenSAFELY organisation
2) User1 creates a new draft
3) User2 is a member of the OpenSAFELY organisation, so can also edit the codelist.  User2 changes the owner of the codelist to themselves.
4) Now the codelist which was available at `codelists/opensafely/foo` is no longer accessible
5) User1 can still see the draft they created, but the codelist itself  is now owned by User2.  User1 can still update the draft, put it into review, and publish it.

I don't think that anyone in an organisation should be able to arbitratily change the owner of a codelist that can be shared by others - possibly not the slug either (basically anything that makes up the canonical URL).  I'd propose that after first publication, the owner/name/slug for an organisation-owned codelist should be locked (or perhaps restricted to organisation admins), so if another user has a URL for a codelist, it might point to a different version in future, but it shouldn't become invalid (the URL issue per se might be handled by codelist DOIs in future, so we might be able to allow name/slug changes, but the owner controls access, so shouldn't change).

**Comment by inglesp** [comment]
> Now the codelist which was available at `codelists/opensafely/foo` is no longer accessible

Changing the owner of a codelist creates a new `Handle`, but the old `Handle` still exists -- so requests to codelists/opensafely/foo will redirect to codelists/user2/foo.

There's still an edge case about people taking ownership of organisation-owned codelists when there is a draft that's owned by another member of an organisation.  I'm not sure what we should do here.

**Comment by rebkwok** [comment]
OK, I didn't realise the old handles would redirect.  In that case, I guess this is not an issue, and I'd expect that changing ownership (especially from org to user) isn't something that would happen often
