### ISSUE TITLE
Review codelists - avoidable hospitalisations

### ISSUE THREAD

**Issue by markagreen** [opensafely-core/opencodelists#1131]
Hi

I am involved in a project using OpenSAFELY for studying trends in avoidable hospitalisations. Please can I submit my codelists for review. I am unable to do this on the main opencodelists website and was suggested to raise this as an issue here.

The main codelist is for ambulatory care sensitive conditions which currently does not exist on the website. The codelist can be found [here](https://www.opencodelists.org/codelist/user/mgreen/ambulatory-care-sensitive-conditions/1b9d1a9e/)

I have also split these codes into the three subtypes - acute, chronic and vaccine preventable. These are all combined into one codelist above, but I also would like three seperate lists for when I come to do the analyses (hence the need for three additional lists). Their individual links are:

- [Acute](https://www.opencodelists.org/codelist/user/mgreen/ambulatory-care-sensitive-conditions-acute/375f4dc9/)
- [Chronic](https://www.opencodelists.org/codelist/user/mgreen/ambulatory-care-sensitive-conditions-chronic/506ec0fe/)
- [Vaccine Preventable](https://www.opencodelists.org/codelist/user/mgreen/ambulatory-care-sensitive-conditions-vaccine-preventable/1e4fda94/)

Finally, could I also have the following reviewed - emergency urgent care sensitive [here](https://www.opencodelists.org/codelist/user/mgreen/emergency-urgent-care-sensitive/34ac8dd3/). These are similar, but based on a different different of avoidable hospitalisations.

Best

Mark

**Comment by Jongmassey** [comment]
Hi Mark, I think I gave you the wrong repository for codelist development issues - can you re-post this issue here https://github.com/opensafely/codelist-development and I'll close this one. Thanks.
