### ISSUE TITLE
Import TPP's Y-Codes

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/opencodelists#116]
Our SQL Server instance is running on covid.ebmdatalab.net.

There's a script at `/home/seb/load_backup.sh` that does the loading.

Accessing the dummy data over pyodbc is illustrated here https://github.com/opensafely/tpp-sql-notebook/blob/master/notebooks/tpp-schema.ipynb

**Comment by rebkwok** [comment]
Duplicate of #1307 and to be done via [this workspace](https://jobs.opensafely.org/datalab/opensafely-testing/tpp-ctv3-codes/) now
