### ISSUE TITLE
Don't ignore quotes when reading codelists from csv files

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opencodelists#1210]
When reading codelists from csv files, quotes are ignored:

https://github.com/opensafely-core/opencodelists/blob/8a0cb0caeab57f303e25dc20e3821b901dd7bf65/codelists/forms.py#L96

Unfortunately, this means that a line like this:

```
a,"b,c",d
```

will be read as

```
["a", "b", "c", "d"]
```

rather than as

```
["a", "b,c", "d"]
```

and raise an error.

@alexwalkerepi suggests removing the quoted commas, to work around the issue, meaning the line should look like this:

```
a,"bc",d
```

Reported by @andrewscolm in [this Slack thread](https://bennettoxford.slack.com/archives/C33TWNQ1J/p1651050772425919).

**Comment by andrewscolm** [comment]
Alex's suggestion of replacing commas with semi-colons works as a workaround.
