### ISSUE TITLE
Server Error (500) when creating codelists

### ISSUE THREAD

**Issue by andrewscolm** [opensafely-core/opencodelists#1213]
I am getting a Server Error (500) when I try to create a codelist via https://www.opencodelists.org/users/candrews/new-codelist/

When I create the codelist via https://www.opencodelists.org/codelist/user/candrews/add I also get a Server Error (500). If I try to re-submit it I get a message saying

> There is already a codelist called `codelist_name`

but I cannot find the created codelist in `my codelists`

**Comment by iaindillingham** [comment]
Are you supplying CSV data when creating a codelist? If so, then could you attach it to this issue? (You can do this by dragging-and-dropping the file to a new comment.) What was the codelist called?

**Comment by andrewscolm** [comment]
Thanks @iaindillingham 

I was tried two different csv files. For https://www.opencodelists.org/users/candrews/new-codelist/ I was using ||

[prelim_ethnicity.csv](https://github.com/opensafely-core/opencodelists/files/8582046/prelim_ethnicity.csv)

**Comment by andrewscolm** [comment]
and for https://www.opencodelists.org/codelist/user/candrews/add I used 
[SNOMED_used.csv](https://github.com/opensafely-core/opencodelists/files/8582087/SNOMED_used.csv)


and tried naming the codelist `ethnicity_in_tpp` and then `ethnicity in tpp`
