### ISSUE TITLE
Error adding dm+d codelists

### ISSUE THREAD

**Issue by LFISHER7** [opensafely-core/opencodelists#1234]
If you add a dm+d codelist as SNOMED rather than dm+d it throws a 500 error.

> I found that when I selected dmd as the coding system it was fine (https://www.opencodelists.org/codelist/user/alexorlek/antituberculosis-drugs-antibacterials/7817e3dc/). But I previously selected SNOMED-CT and this led to a server error (https://www.opencodelists.org/codelist/user/alexorlek/aminoglycosides-antibacterials/2a36ca47/)

**Comment by bloodearnest** [comment]
These both should have been deleted now
