### ISSUE TITLE
Definition builder: "unresolved" view should update to only show resolved things

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/opencodelists#124]
Clicking on a plus/minus in this view should cause an item to fade out over a couple of seconds.

This would allow the view to act as a worklist, and you know you've finished a term when that view is empty.

**Comment by brianmackenna** [comment]
This would be nice but it would need to be very easy to fix mistakes from stray mouse clicks.

Potentially instead of empty view could they fly into an inclusion/exclusion basket at the bottom of screen?
