### ISSUE TITLE
Definition builder: add a key and/or tooltips

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/opencodelists#127]
We need to explain somehow what the three states of the add/remove buttons mean; and what black, grey and red text means in node descriptions.

For red text, it would be great to indicate the cause of the conflict ("X is implicitly included in term search A, but implicitly excluded in term search B").

I think tooltips would probably be fine for this.  In the case of red text, perhaps this popover would also be the location for resolving the conflict?

**Comment by rebkwok** [comment]
I think this is done, by way of popovers by each code that indicate if they're included/excluded and, if implicitly included/excluded, by which parent
