### ISSUE TITLE
Autoconvert BNF codes to dm+d codes

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#1334]
In order to use `with_these_medications` in OpenSAFELY you must use a codelist in the dm+d form.

However most medications codelists are built using pseudoBNF code structure, then converted to dm+d using a feature on OpenCodelists, then downloaded and finally reuploaded to the site on a hidden page that allows editors to add raw csvs.

This takes a little time, isn't well documented and also introduces the chance of errors when someone downloads and opens with excel corrupting the identifier before uploading and a video with some of the workflow.

**Would it be possible to add an autoconvert feature?**

There is some background in this [draft blog](https://docs.opensafely.org/codelist-creation/#build-a-simple-medication-codelist) on differences between medicine terminoliges.

**Comment by josephignace** [comment]
Hi,
I found a work around that help me to use dm+d codes after creating a PseudoBNF codelist. Once the list is ready to use, Opencodelist allows to download the list as "dm+d", such file can be copied-pasted into the local_codelist folder. Then it can be used. It may not be the best solution, but it works.
