### ISSUE TITLE
Consider adding a confirmation prompt on discarding a draft codelist

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/opencodelists#1349]
Suggested by @richiecroker: this would prevent users from losing work accidentally on clicking discard.

**Comment by inglesp** [comment]
This'll require poking around in the [codelistbuilder.jsx](https://github.com/opensafely-core/opencodelists/blob/main/static/src/js/builder/codelistbuilder.jsx).

**Comment by rebkwok** [comment]
FIxed by #1374
