### ISSUE TITLE
Record coding system releases compatibility for codelist versions

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1441]
A codelist version has a record of the coding system release that was used to create it.  It may be compatible with subsequent releases of the coding system, and we should record that.

How can we tell if a codelist version is compatible?
1) If it was created with searches, rerun the searches with the new release.  If all searches bring back identical results, the codelist version is compatible.
2) For versions without searches, if it has a cached hierarchy, we can recreate the hierarchy using the new coding system release and the version's codes.  If the old and new hierarchies match, the codelist version is compatible.
3) If there are no searches and no cached hierarchy, the best we can do is to confirm that the version is not _incompatible_ - ie. there are no codes on the version that are missing in the new relase.  This is probably not enough to be able to say that it is compatible, since we can't know if any relationships between codes formed part of the author's intention, or if any of those relationships have changed.

We need to:
- check for compatible versions after importing a new release (we can limit this to versions that were created or compatible with the previous release)
- record releases that the version is compatible with
- display compatible releases on the version/builder pages

**Comment by inglesp** [comment]
This is really interesting, thanks.

> 1. If it was created with searches, rerun the searches with the new release. If all searches bring back identical results, the codelist version is compatible.

Agree.  This also holds in the case where a codelist was created by uploading a CSV, and then when the user does some searches that cover all of the codes in the CSV.

> 2. For versions without searches, if it has a cached hierarchy, we can recreate the hierarchy using the new coding system release and the version's codes. If the old and new hierarchies match, the codelist version is compatible.

I'm not sure we can be sure.  We can certainly say that we don't know that the codelist version is incompatible with the new release, although that's probably not very reassuring!

But suppose in release N, there's a hierarchy that looks like:

```
parent
├ child 1 (included, with any descendants)
├ child 2 (included, with any descendants)
├ child 3 (excluded, with any descendants)
└ child 4 (excluded, with any descendants)
```

Then in release N+1, the hierarchy looks like:

```
parent
├ child 1 (included, with any descendants)
├ child 2 (included, with any descendants)
├ child 3 (excluded, with any descendants)
├ child 4 (excluded, with any descendants)
└ child 5
```

Should we include or exclude child 5?  I think it would need human input.  But it should be possible to identify this situation.  And it might also be possible to identify some situations when a codelist without searches is compatible with a new version.  (More brandy required.)

Or could we step around this by insisting that users do sufficient searches after uploading a codelist?  (But this wouldn't work in cases where we host a codelist from eg PRIMIS...)

> 3. If there are no searches and no cached hierarchy...

Once we use the dm+d hierarchy, what codelists does this affect, apart from those were we don't have any releases, such as OPCS-4?

**Comment by rebkwok** [comment]
I think in the case of hierarchies, if the hierarchy with the new and old version is identical, we can say it's compatible.  That's a pretty stringent check, and there may be some versions that could be considered compatible that it misses.

In the example you gave above, where we've got a new child 5 in release N+1, the hierarchy would be different, so it wouldn't be marked as compatible.  
> parent
> ├ child 1 (included, with any descendants)
> ├ child 2 (included, with any descendants)
> ├ child 3 (excluded, with any descendants)
> ├ child 4 (excluded, with any descendants)
> └ child 5
If it had been created with a search that previously returned child 1-4, and still does, it would be marked as compatible, but without searches, we don't know enough to say.

Possibly we could look at the included/excluded codes and try to work out if we can update it, but I think that's out of scope for checking compatibility.  I'm not considering that we update any codelists or that we notify users of codes that are now ambiguous in a new release at this point, just to record releases that are definitly compatible.

**Comment by rebkwok** [comment]
> If there are no searches and no cached hierarchy...
> Once we use the dm+d hierarchy, what codelists does this affect, apart from those were we don't have any releases, such as OPCS-4?

None; dm+d is the only one without hierarchy. There might be old ctv3, if we split out ctv3 and tpp-ctv3 as we discussed, depending on whether we implement it in ctv3 (currently it only uses tpp-ctv3 models for the hierarchy)
