### ISSUE TITLE
Error converting BNF to dm+d

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opencodelists#1463]
@speed-vm is trying to convert [this BNF codelist][1] into a dm+d codelist. However, OpenCodelists errors with

> CSV file contains 1465 unknown code -- the first (321112001) is on line 1 (dm+d release unknown, valid from 1900-01-01)

@richiecroker thinks the issue might relate to a new drug. For more information, see [this Slack thread][2].

---

![Screenshot 2022-12-05 at 18-01-21 OpenCodelists](https://user-images.githubusercontent.com/477263/205709157-4894f9c7-a67f-46d1-b684-dce1031f67fb.png)

[1]: https://www.opencodelists.org/codelist/user/speed-vm/medications-addictive-medicines/79636c0f/
[2]: https://bennettoxford.slack.com/archives/C31D62X5X/p1670258003662399

**Comment by Jongmassey** [comment]
But those dm+d codes *do* appear to be valid, though?

**Comment by richiecroker** [comment]
@Jongmassey yes they are - at least some of them are, which is not what this is saying!

**Comment by rebkwok** [comment]
Fixed by #1465
