### ISSUE TITLE
Write script to convert BNF codelists to dm+d

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#1496]
@kevwing is working on a study with a lot of BNF medication codelists.  He's asked for help converting these to dm+d codelists so that he can use them with `patients.with_these_medications()`.

We should be able to write a script to convert these automatically for him.  The script should take, as input, a file containing the full slug of the BNF codelist version, and create new codelists.  The new codelists should:

* be in in the same organisation as the original
* have `-dmd` appended to the codelist slug
* include a link to the original codelist version in the methodology
* have codes generated by [`mappings.bnfdmd.mappers.bnf_to_dmd`](https://github.com/opensafely-core/opencodelists/blob/main/mappings/bnfdmd/mappers.py)

The codelists that need to be converted are in the BNF tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1gB6MsAeyGyYk_uo8TPcR4RMRkNf09lpdegJWdtZgPws/edit#gid=823327680).

**Comment by rebkwok** [comment]
@inglesp This all seems clear.  As something similar has been requested before, can we maybe combine it with #1334, or at least write the code in such a way that it could be used for auto-conversion from the UI too?  A function that takes a BNF codelist version, converts it to dm+d and and creates a new codelist as described above could be called by both the proposed script for this issue, and from a "convert-to-dm+d" button on a BNF codelist page.

**Comment by inglesp** [comment]
Writing the script with an eye to addressing #1334 makes sense, good idea.

**Comment by inglesp** [comment]
> Should the new dm+d codelists also have the same description as the original?

Yes, I think so.  The methodology should link to the original BNF codelist though.

> Should they have the same references as the original (if there are any)?

Yes.

> Should their status be Published or Under Review?

I'd go for Published.

> All the codelists in the spreadsheet are user codelists, not organisation ones - should they be created under the same user (I'm assuming yes)?

Yes.

**Comment by rebkwok** [comment]
@kevwing These codelists have been converted now; attached is a spreadsheet of BNF version to new dm+d codelist
[Variables_ post-COVID symptoms, diagnoses, prescriptions - BNF_converted.csv](https://github.com/opensafely-core/opencodelists/files/10448746/Variables_.post-COVID.symptoms.diagnoses.prescriptions.-.BNF_converted.csv)
