### ISSUE TITLE
show differences between codelists

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#15]
It would be great to have a feature that allows comparison of codelists from the same coding system.

i.e. you select both and it say this list of codes is in x but not in y.

There are a few use cases for this
1. When codelists are built from hierarchies it is inevitable that new children will  over tim. It may be useful to see differences between present day versus a year ago when codelists was generated.
2. Two papers assessing the same question may have created different codelists but not fully explained the rationale. Allowing  quick check of differences might be useful (if a bit niche!)
3. At OpenPrescribing we from time to time are contacted by users saying your code doesn't match NHS BSA ePACT2 or PrescQIPP -> it would be really useful if users (and me and @rich) could do a quick check on differences on a site like this. Hopefully prganisations like PrescQIPP, NHS England, BSA etc. will contribute to the project.

**Comment by rebkwok** [comment]
Closing - done

**Comment by brianmackenna** [comment]
I won't reopen but just to say this feature is not very well known about to users............could we prioritise this issue to help with getting more use?

https://github.com/opensafely-core/opencodelists/issues/1148

**Comment by rebkwok** [comment]
The ticket for documenting it will stay open, but I think there's a lot of other things that will be higher priority.  When we have the coding system releases fully implemented, I think there will be a strong case for making it more visible in the interface and docs.  I've added it to #1446
