### ISSUE TITLE
Display terms from old CSV data in codelist diffs when lookup terms are unavailable

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1555]
The diff view can be used to compare different versions of the same codelist - in particular, it's being used to look at stale dm+d codelists.  dm+d codes can be retired and are therefore not present in newer releases of the coding system.

The diff looks up terms for the codelist version's codes using its respective coding system release. However, for codelist versions that pre-date the coding system releases, the coding system release is just whatever was the latest then, not necessarily the one it was actually created with.  If a code doesn't exist in that coding system release, the term is just shown as "Unknown".  

e.g. https://www.opencodelists.org/codelist/opensafely/methotrexate-oral/041a8320/diff/0b17e9f5/

For codelist versions created by old-style CSV upload (which is all dm+d codelist versions), we can get the terms from the original upload, even if they're not valid in the coding system lookup.  i.e. that codelist version with all the unknowns in the diff is this one: https://www.opencodelists.org/codelist/opensafely/methotrexate-oral/041a8320/#full-list

It would be helpful to users to show the term from the original upload (labelled with something like "not found in coding system data").

**Comment by Jongmassey** [comment]
Yes, I agree, it would be useful to show the user the term from the original upload, and also very useful to indicate somehow that this code is no longer present in the compared version
