### ISSUE TITLE
Automatically update codelists

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#17]
Some codelists will be manually curated but a lot will be select all children from parent.

Now the children will probably change overtime so it would be good to have a feature where you could take a list that was made a year ago and rerun it to include all children that exists today. I know with medicines they can change month on month with new or discontinued products.

Linked to #15  as well.

**Comment by rebkwok** [comment]
Closing as should be superceded by recent work on coding system releases
