### ISSUE TITLE
Updated high-risk groups codelists

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opencodelists#1771]
From @wjchulme:

> In September, PRIMIS supplied updated codelists for the high-risk groups defined in Green Book chapter 14a, where eligibility criteria for covid vaccination is defined. I don't think the high-risk groups have changed much -- the main change I can see is that pregnancy is now a high-risk group -- although it will need a more detailed check. The original codelists were uploaded to OpenCodelists under [the PRIMIS Covid Vaccination Uptake Reporting organisation](https://www.opencodelists.org/codelist/primis-covid19-vacc-uptake).
>
> What's the best approach to getting the new codelists to OpenCodelists?

Will makes two suggestions:

> We could upload them to a new organisation, e.g. primis-covid19-vacc-sep2023. This may be technically straightforward, but it wouldn't be obvious to users that more up-to-date codelists are available.
>
> We could update the codelists in-place. This may be technically harder (or not!) but it would be important to be able to easily access older versions in `codelists.txt` for studies covering earlier time periods.

An Excel file containing the updated codelists is attached to the associated Slack thread.[^1]

[^1]: https://bennettoxford.slack.com/archives/C010SJ89SA3/p1702548265776079

**Comment by wjchulme** [comment]
Thanks for opening this issue, Iain. 

A follow up question. If we wanted to capture _all_ prior incremental updates to these codelists, as provided in a series of spreadsheets, is that especially complicated?

More generally, I would be very happy to help with these updates directly, if I new more about how to add codelists via the backdoor (i.e. not using the manual codelist selector and not uploading standalone codelist files). For instance, if a json file derived from all spreadsheets could be easily ingested, then I'd be happy to create it.

**Comment by wjchulme** [comment]
Thanks @rebkwok. Both myself and @emprestige have looked at this and we're happy that everything is in order. We'll let you know if we spot any issues when we go to use the new codelists. Thanks!
