### ISSUE TITLE
Remove a few published codelists for user

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/opencodelists#1805]
https://bennettoxford.slack.com/archives/C069SADHP1Q/p1705579887970719

There's a list of specified codelists requested for removal, some with "test" names.

Unfortunately, the way to delete codelists is currently via the Django shell.

There's further discussion on what the process should be in that thread.

When done, please reply in thread to confirm it for the user: https://bennettoxford.slack.com/archives/C33TWNQ1J/p1705570698964859

**Comment by StevenMaude** [comment]
The deletion is now done. I'll write it up.

**Comment by StevenMaude** [comment]
https://github.com/ebmdatalab/team-manual/pull/629

**Comment by StevenMaude** [comment]
This is now done as #1825 got merged.
