### ISSUE TITLE
Import new BNF data and BNF-dm+d mappings

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/opencodelists#1814]
New BNF data has been [requested](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1706107758047059) via tech-support.

Although not actually required for that specific tech-support request, there is a new release of BNF available which needs to be imported: follow [instructions for importing](https://github.com/opensafely-core/opencodelists/tree/main/coding_systems/bnf#readme)

Also the BNF to dm+d mapping should be updated too, as per [these instructions](https://github.com/opensafely-core/opencodelists/blob/main/mappings/bnfdmd/README).

**Comment by Jongmassey** [comment]
Done both as per the instruction. There wasn't much in the way of console output for the bnf mappings management command but started a django shell and checked `Mapping.objects.count()` matched the row count (for non-null BNF codes) in the supplied spreadsheet.
