### ISSUE TITLE
Fix recent BNF SNOMED Mappings

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opencodelists#1898]
from https://www.nhsbsa.nhs.uk/prescription-data/understanding-our-data/bnf-snomed-mapping

> Please note- A corruption in the BNF Code has been identified within December 2023's SNOMED data. This has now been corrected and the file has been re-ran and replaced. This can be accessed under the Previous Excel versions of SNOMED drop down at the bottom of this page. Apologies for any inconvenience caused.
>Please note: It has been identified that the BNF Name populated in the January 2023 and February 2023 mapping file has been restricted to a maximum of 20 characters instead of the normal maximum 60-character drug limit and 100-character appliance limit.
>We have re-run these two files and replaced the current published files for these two months.

**Comment by StevenMaude** [comment]
I've completed the reimport:

```
>>> from mappings.bnfdmd.models import Mapping
>>> Mapping.objects.count()
325843
```

Comparing against the XLSX file:

```
>>> import pandas as pd
>>> df = pd.read_excel("BNF Snomed Mapping data 20230321.xlsx")
>>> df.columns
Index(['Presentation / Pack Level', 'VMP / VMPP/ AMP / AMPP', 'BNF Code',
       'BNF Name', 'SNOMED Code', 'DM+D: Product Description', 'Strength',
       'Unit Of Measure', 'DM+D: Product and Pack Description', 'Pack',
       'Sub-pack'],
      dtype='object')
>>> df[df["BNF Code"].notna()]
…
[325843 rows x 11 columns]
```

**Comment by StevenMaude** [comment]
I'm going to tidy up the documentation slightly, and then this can be closed.
