### ISSUE TITLE
About OpenCodelists Section

### ISSUE THREAD

**Issue by annaschultze** [opensafely-core/opencodelists#19]
I think it'd be useful to have a brief "About Us" or similar explaining what OpenCodelists is, that it's part of OpenSafely, any funding, who to contact for questions and potentially some form of license statement about how these codelists can be used? + contributer guidelines for later down the line?

**Comment by brianmackenna** [comment]
Some [draft lines](https://docs.google.com/document/d/1N2M_MmBqOVVm1vbXDc69PBHF9XpyXIi7ZzzVrnvqv-Y/edit) of each included coding format with onward linkage

**Comment by brianmackenna** [comment]
we should write #35 at the same time.
