### ISSUE TITLE
Handle.MultipleObjectsReturned  when converting BNF codelist to dm+d

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opencodelists#1968]
From [Sentry issue here](https://ebm-datalab.sentry.io/issues/5400826401/?alert_rule_id=1877862&alert_type=issue&notification_uuid=78071205-733f-43f8-b8f6-1f46a6418d21&project=5248013&referrer=slack)

**Comment by lucyb** [comment]
@Jongmassey to update the issue with the details and then close.

**Comment by Jongmassey** [comment]
We believe this is related to moving codelists between organisations, although we've not seen it before or since, and are unable to replicate.
