### ISSUE TITLE
Should `codelist_update` allow a user to upload a new CSV file?

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opencodelists#2087]
The `codelist_create` view allows a user to upload a CSV file to create an "old style" codelist.

https://github.com/opensafely-core/opencodelists/blob/55332b83d5427b9bdc6aecf2710916ca4d8fb4a9/codelists/views/codelist_create.py#L19-L25

The CSV file need not adhere to a schema; the data in the CSV file are validated and cleaned and associated with the instance.

However, the corresponding `codelist_update` view doesn't allow a user to upload a new CSV file to update the codelist.

https://github.com/opensafely-core/opencodelists/blob/55332b83d5427b9bdc6aecf2710916ca4d8fb4a9/codelists/views/codelist_update.py#L14-L22

@andrewscolm created a codelist from a CSV file that had `code`, `term 1`, and `term 2` columns. However, he couldn't update this codelist from a new CSV file.[^1] Possibly Colm should create a new codelist?

It's not clear whether modifying `codelist_update` is desirable, given the distinction between "new style" and "old style" codelists.

[^1]: https://bennettoxford.slack.com/archives/C31D62X5X/p1728646729192689

**Comment by lucyb** [comment]
We should speak to @andrewscolm and see how much effort it will be for him to create a new codelists and what implications there are if he does this.

**Comment by andrewscolm** [comment]
To update: this issue was due to opening the csv file with excel rather than the `codelist_update` function.

**Comment by iaindillingham** [comment]
Closing, because I think Colm has resolved the issue.
