### ISSUE TITLE
Improve process for updating BNF SNOMED mapping

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/opencodelists#2099]
The NHS [publishes](https://www.nhsbsa.nhs.uk/prescription-data/understanding-our-data/bnf-snomed-mapping) BNF SNOMED mapping files monthly. The updates are usually published towards the end of the month.

The date of the mapping file given on the website is different from the datestamp in the filename. This is because the filename datestamp is the date which the mapping file was generated, and the date published on the website is the date to which the mappings are up to date. There is usually a 3 month lag.

For example, at the time of writing the most recent update file is the "July 2024" update, but the mapping file is called `BNF Snomed Mapping data 20240923.xlsx`

The current [mapping import process](https://github.com/opensafely-core/opencodelists/blob/main/opencodelists/management/commands/import_mapping_data.py) takes no record of the filename used in the import, and thus it is not possible to ascertain how up to date the BNF-SNOMED mapping on OpenCodelists is.

There has been a recent tech support issue querying why mappings were missing and I have memories of missed mapping updates being a problem in the past.

We should improve this such that:

* Updates to this mapping file are done in a timely fashion
* It is easy to check that the updates have been done

We should consider:
* Surfacing the mapping file update date to users
* Automating the getting of these updates as per we do for other coding systems - [Draft](https://github.com/opensafely-core/opencodelists/pull/2100)
* ~~Setting a Bennett Bot reminder to apply these updates~~ ✅

**Comment by Jongmassey** [comment]
Here's some ideas based on the TRUD downloader class https://github.com/opensafely-core/opencodelists/pull/2100

**Comment by iaindillingham** [comment]
Time box to half a day.
