### ISSUE TITLE
Document restoring core and coding system release DBs from droplet backup

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/opencodelists#2128]
Document the process of restoring the coding system release DBs from a droplet backup. Doing so will mean actually creating a new droplet, and restoring a droplet backup into it, to verify that the process works. #2116 defines the terms _coding system release DBs_, _droplet backup_, and _droplet_.

**Comment by lucyb** [comment]
I'm closing this as I believe it will be made redundant by https://github.com/opensafely-core/opencodelists/issues/2225 and a move over to Digital Ocean Block Storage.

**Comment by mikerkelly** [comment]
This was reopened as if we rely on the droplet storage as a fallback restore option as mentioned in #2246 it would be beneficial to verify that we can actually do that and understand what it would involve.
