### ISSUE TITLE
Dependabot is not updating all Python dependencies

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/opencodelists#2165]
For example, the OpenTelemetry dependencies are old, yet there are no Dependabot pull requests for these packages.

We may want to switch to the opensafely-core/update-dependencies-action for the Python dependencies.

Dependent on https://github.com/opensafely-core/opencodelists/issues/1817

**Comment by lucyb** [comment]
[This](https://github.com/opensafely-core/opencodelists/issues/1641) may be relevant for the OTel dependencies. Of course, Dependabot definitely has other problems as well.

**Comment by iaindillingham** [comment]
Thanks for this, @StevenMaude. Something to consider for the next deck-scrubbing.

**Comment by StevenMaude** [comment]
Some of the issue is that we have a [pull request limit of 20 set](https://github.com/opensafely-core/opencodelists/blob/35d334b0219f21de7aedbb15fede909c6b94774f/.github/dependabot.yml#L11), but nonetheless there are dependencies that Dependabot still won't update.

**Comment by StevenMaude** [comment]
In a 2024-12-10 planning meeting, we suggested switching to the OpenSAFELY [update-dependencies-action](https://github.com/opensafely-core/update-dependencies-action/).

We probably should get the dependencies more up-to-date before trying this switch over. Some dependencies are still quite old. Weekly runs from then on should be a more incremental set of changes.

**Comment by mikerkelly** [comment]
I would like us to at least consider alternative third-party solutions to updating dependencies. That could just mean understanding such thinking that was done before implementing [update-dependencies-action](https://github.com/opensafely-core/update-dependencies-action/). If we use a homebrew solution, the organization needs to maintain that and it's likely not as fully-featured. However if it fulfils our needs simply and effectively that could be fine.

**Comment by StevenMaude** [comment]
What to replace Dependabot with is a recurring discussion we've had a couple of times. Renovate has been mentioned a couple of times in the past, but it doesn't seem like it's been compelling enough for us to commit to switch to it.

At least Airlock, ehrQL and the metrics repositories — and possibly more — are using this action now.

One downside with `update-dependencies-action` is that all dependencies are updated together, which means if one package update fails CI, then it forces fixing the issue before any more updates will automatically work.

However, Dependabot is completely broken right now. It is not reliably producing updates for all packages. For now, this allows update PRs to hopefully at least be generated, and we can add reviewing and merging them to the regular rota we have for repositories, without delay.

We can still always revisit the decision in future and amend it if we think there's a better solution. It may be that Dependabot works better with, say, `uv` than our use of `pip-tools` and [constraints](https://github.com/dependabot/dependabot-core/issues/2272).
