### ISSUE TITLE
Reduce size of core database

### ISSUE THREAD

**Issue by mikerkelly** [opensafely-core/opencodelists#2215]
We are currently have around 50GB free on dokku3. The core OpenCodelists database is 4.1GB, zippable to 1.1GB in backups. #2151 seems to increase the space requirement for backups by about 20GB. We should consider vacuuming](https://sqlite.org/lang_vacuum.html) the database or [other approaches to reducing its size](https://thelinuxcode.com/reduce-sqlite-file-size/) 

We might also consider increasing the space available on dokku3 if that's more  cost-effective.

Any work should be done locally on a backup to evaluate effectiveness before considering restoring the prod DB from the reduced-size backup.

A quick experiment with vacuuming seems to show around a ~5% space saving:

```bash

sqlite3 db.sqlite3 ".backup /storage/tmp/test_backup_db.sqlite3"
ls -lh tmp/test_backup_db.sqlite3
-rw-r--r-- 1 10003 10003 4.1G Dec 10 08:58 tmp/test_backup_db.sqlite3
sqlite3 tmp/test_backup_db.sqlite3 "VACUUM"
ls -lh tmp/test_backup_db.sqlite3 
-rw-r--r-- 1 10003 10003 3.9G Dec 10 09:03 tmp/test_backup_db.sqlite3
rm tmp/test_backup_db.sqlite3 
```

As the coding systems databases are read-only I don't expect VACUUM will benefit them but it would be worth experimenting on a backup of one with some of the same techniques to see if they can benefit.

**Comment by lucyb** [comment]
I'm closing this as I believe it will be made redundant by #2225 and a move over to Digital Ocean Block Storage.
