### ISSUE TITLE
Password Reset Flow

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/opencodelists#275]
It would be useful to have a page where an Admin can reset another Users password, ideally without the admin inputting the password for them.

With the User activation flow we already have part of this in place, the activation URL, but this redirects to `/` when the User is already activated.  So what we could do is add a simple list page for Users, with a button for each User, which does:
* set `is_active` to `False`.
* redirect the Admin to `/added/<username>`

The Admin can then send the displayed URL to the User who can use it to go and set their password.

**Comment by rebkwok** [comment]
Users can now reset their own passwords
