### ISSUE TITLE
Different table formats and code corruptions within existing codelists

### ISSUE THREAD

**Issue by abelardy** [opensafely-core/opencodelists#28]
The April 24th code list distros have some irritating technical characteristics that would be helpful to address, and some puzzling content issues that would be helpful to clarify:

1. They're encoded with UNIX- rather than DOS style line termination except the final line. Pretty much every other terminology and classification machine readable resource on the planet is distributed using DOS CRLF line termination, including the final line. Don't ask why; they just empirically are.
2. They're comma separated and so also optionally quote delimited wherever the field value itself contains a comma. Universally Tab separated and therefore with no field delimitation necessary is much easier to post-process.
4. There are 7 different table schemas
6. opensafely-chemotherapy-or-radiotherapy-2020-04-15 contains corrupted (truncated) codes e.g. at lines 4-12, 15-18 etc.
7. opensafely-stroke-2020-04-21 contains READ2 codes from Line 209 onward; this block also includes one code at line 220 (ZLEP.00) that is neither a known READ2 code nor a TPP local Y-code extension to CTV3.
8. Almost all of the codelists - both CTV3 and SNOMED (drug) ones - include significant volume of codes that are inactive or extinct within the relevant underlying terminology, but not **all** such clinically relevant inactives. What is the basis for including/excluding some? For example, opensafely-aplastic-anaemia-2020-04-24 includes these six Extinct CTV3 codes:

D200. (Anaemia: [constitutional aplastic] or [familial hypoplastic]) or (pancytopenia with malformations) or (Blackfan - Diamond syndrome)
D2000 Anaemia: [congenital hypoplastic] or [constitutional aplastic without mention of malformation]
D2003 (Red cell: [constitutional aplasia or hypoplasia] or [congenital pure aplasia] or [congenital hypoplasia]) or (Blackfan - Diamond syndrome)
D201. Anaemia: [acquired aplastic] or [normocytic due to aplasia]
D2011 Anaemia: [aplastic due to drugs] or [hypoplastic due to drug or chemical substance]
XE14g Anaemia: [aplastic and other] or [aplastic] or [hypoblastic]

...but not this one:

D201z Anaemia: [acquired aplastic NOS] or [acquired pure red cell aplasia] or [red cell hypoplasia] or [secondary red cell aplasia or hypoplasia NEC]

**Comment by inglesp** [comment]
Hi @abelardy, thanks for your feedback.  Sorry it's taken a while to respond!

The project does just enough to support the early OpenSAFELY analyses, and as you've spotted, there are all sorts of warts.  If/when OpenSAFELY gets funding we'll spend more time either building this properly, or properly evaluating alternatives.

Thanks for reviewing the validity of the codelists.  I've raised #34 to cover automatically checking that codes are valid, and we'll review the impact of the invalid codes that you've found.  I'll talk to our clinical folks about whether the omission of the extinct codes is deliberate.

I understand you're talking to Amir soon -- I'd like to join part of this call to understand your view on how a tool like this could fit into the broader ecosystem.

**Comment by rebkwok** [comment]
Closing this issue as it relates to a very early incarnation of OpenCodelists, and there have been significant improvments to check validity of codes on upload, as well as to fixes to some specific codelists (e.g. #71)
