### ISSUE TITLE
Missing Snomed code - 846743000 | Cataract present (situation) |

### ISSUE THREAD

**Issue by Auselan** [opensafely-core/opencodelists#364]
In my code list https://codelists.opensafely.org/builder/4fc3bcff/ I found a problem ?fault in code tables

Context
I am building a list of 'pretty much anything to do with the eye' for a merge field related to a referral.  The use case is that an Ophthalmologist may find the coded history of eye diseases and findings invaluable, but those codes do not necessarily appear on a traditional referral letter, if they were not marked as a Problem.

Detail
I want this code in my list: http://www.diseasesdatabase.com/snomed/846743000 =  846743000 | Cataract present (situation) |

For some reason, when I searched for "cataract present", I was presented with the remarkably similar (finding) tree of 162811006 | On examination - cataract present (situation) | which has the same ancestor of 373573001 | Clinical finding present (situation) | but is not the same code, but not the code tree for 846743000 .  Screenshot
![image](https://user-images.githubusercontent.com/32044548/100243009-5457b500-2f2d-11eb-87a8-b2e3feb0b77c.png)

When I search for the ancestor code, the code is not present in OpenSAFELY's hierarchy:
![image](https://user-images.githubusercontent.com/32044548/100244475-ddbbb700-2f2e-11eb-8abd-fe2a1a04b06d.png)

It is definitely a genuine code - see https://termbrowser.nhs.uk/?perspective=full&conceptId1=846743000&edition=uk-edition&release=v20201028&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104 for a further validation.

**What has gone wrong here?**

**Comment by Auselan** [comment]
Just noticed another discrepancy:

Diseases Database 768600002 | Product containing coumarin (product) |
http://www.diseasesdatabase.com/snomed/768600002
![image](https://user-images.githubusercontent.com/32044548/100245593-1f009680-2f30-11eb-9102-2fa543c5c1b6.png)

versus OpenSafely:
![image](https://user-images.githubusercontent.com/32044548/100245675-3a6ba180-2f30-11eb-970d-89898b41351a.png)

versus NHS term browser:
![image](https://user-images.githubusercontent.com/32044548/100245785-5707d980-2f30-11eb-95dc-f6819e4f56d7.png)

There must be different tables of data going on here?  It looks as if OpenSAFELY's snomed tables are out of sync with the UK tables?

**Comment by inglesp** [comment]
Looks like `846743000 | Cataract present (situation) |` is a fairly new concept:

![image](https://user-images.githubusercontent.com/28734/100251836-20818d00-2f37-11eb-8263-88b1fc23bf08.png)

It looks like we've not imported the latest release.  I'll do so this week.

**Comment by Auselan** [comment]
Ah that would explain my first observation.  What about the second one, the medication? Is that also part of the latest patch?

I suppose this is a good time to bring up the revision of code lists when the hierarchies have changed.

When a new code is added in to an hierarchy, a code list which has a definition of "and all descendents" will be affected,  similarly if a code is made inactive.

Ideally, the tool would do several automated audits.  As someone with responsibility for maintaining a list, I would like a Task to be sent to me to review 

1 which codes will be newly included in my code list because they appear in "descendent" rules of a list you created
2 which codes have become inactive 
3 which codes now show up on your keyword searches that were used to build your list because of the changes to snowed

That would be extremely tight for governance of the integrity of the lists.

I wonder: how does OpenSafely currently behave when a new code enters the hierarchy? Will a list now include the code if it appears because of a rule, or will the Definition be updated, to reflect that that code was not in the original definition?  The latter might be the safest as it doesn't involve changing the list at all, but would leave the list out of date... tricky!

**Comment by inglesp** [comment]
@Auselan I've imported the latest SNOMED releases, and the missing concepts are now showing up:

* [846743000 | Cataract present (situation)|](https://codelists.opensafely.org/snomedct/concept/846743000/)
* [768600002 | Product containing coumarin (product) |](https://codelists.opensafely.org/snomedct/concept/768600002/)

There's some further work to do to work out what to do when importing new SNOMED releases means that more codes match existing searches.  That requires more brain power than I possess on 22nd December!
