### ISSUE TITLE
Title Changes on Codelists 

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#39]
We currently have a codelist titled [Chronic Kidney Disease](https://codelists.opensafely.org/codelist/opensafely/chronic-kidney-disease/). This list was developed to support identification of people with chronic kidney disease using codes indicating end stage renal disease, dialysis or kidney transplant code. Having developed more codelists we don't think the title is a good identifier as people would expect to find long term disease codes (see [BNF more information on stages](https://bnf.nice.org.uk/guidance/prescribing-in-renal-impairment.html)).

We would like to change the name of the codelist to something like `End stage renal disease / transplant` however this will mess up code for previous studies or studies that are currently in production. 

Is putting the doi in the code or the solution? Probably more elegant solutions. We can live with imperfect names for the minute.

**Comment by inglesp** [comment]
It's not essential for a codelist title to match the URL, so if you want to change the title now, you can.

As you've noted, changing the URL will break existing studies.  This is fixable -- we can record old URLs, and redirect -- but I think there are other priorities at the moment.

**Comment by rebkwok** [comment]
No longer applicable; codelist names can be changed now, and old URL s will redirect via Handles.
