### ISSUE TITLE
Review new (converted) SNOMED codelists

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/opencodelists#40]
We now have [code to generate a SNOMED CT codelist from a CTV3 one](https://github.com/opensafely/opencodelists/blob/master/codelists/management/commands/convert_codelist.py), and we've added SNOMED CT versions for each of the codelists that were used in the "factors associated with..." paper.  See eg [Asthma Diagnosis (SNOMED)
](https://codelists.opensafely.org/codelist/opensafely/asthma-diagnosis-snomed/).

For the larger codelists, loading the page can be quite.  I've had to remove the Tree view for SNOMED CT codelists, since (a) it could take several minutes to generate a tree, causing timeouts and (b) the tree view is not very useful -- SNOMED CT concepts often have several parents and so end up appearing tens of times.

The generated codelists will need to be reviewed.  I propose doing this in three steps:

- [ ] @brianmackenna produces SNOMED CT codelists from scratch for a couple of codelists.  We then compare this to the generated codelists.

Once we're happy that the process for generating codelists is as good as it can be...

- [ ] Clinically-clueful people review the 27 generated codelists.  To weed out false positives, we'll create a Google Sheet for each codelist where can either confirm that each code should be included, or mark off those that shouldn't be.  Finding false negatives (ie missing codes) will be harder, and depending on how likely we think this is to happen (based in part on step 1) we may have to produce some tooling.

Once we've reviewed the codelists..

- [ ] Seek feedback from people outside the team.

**Comment by sebbacon** [comment]
> Seek feedback from people outside the team

Specifically SNOMED extensions from ACME

**Comment by rebkwok** [comment]
Closing on the assumption that the codelists referred to were checked and no further action is needed.
@sebbacon @brianmackenna please let me know if there's anything that should be transferred to an updated issue.
