### ISSUE TITLE
Can the "Search Codelists" box appear on every page?

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/opencodelists#410]
... to avoid going back to the home page every time you want to perform a new search 
![image](https://user-images.githubusercontent.com/24392156/101916763-4bb6de00-3bbf-11eb-9c44-a036226255b7.png)

**Comment by rebkwok** [comment]
I don't _think_ this issue is required anymore; the search box is present on each page of paginated codelists and on search results.
