### ISSUE TITLE
Deploy automatically when main is updated

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#49]
This can be done via [ebmbot](https://github.com/ebmdatalab/ebmbot).

**Comment by iaindillingham** [comment]
I'm going to close this issue, as embot is deploying automatically.

**Comment by inglesp** [comment]
> I'm going to close this issue, as embot is deploying automatically.

Afraid it's not, sorry.

**Comment by iaindillingham** [comment]
😢

**Comment by rebkwok** [comment]
Closing as github actions now deploys automatically
