### ISSUE TITLE
Codelist not appearing in search

### ISSUE THREAD

**Issue by annaschultze** [opensafely-core/opencodelists#524]
This may well be something I'm misunderstanding, but this PRIMIS code list https://codelists.opensafely.org/codelist/primis-covid19-vacc-uptake/longres/v1/#full-list does not appear when I search for terms in the heading (such as nursing). Is that something that's meant to not appear?

**Comment by inglesp** [comment]
We're only returning OpenSAFELY codelists in search results at the moment.

**Comment by rebkwok** [comment]
Was fixed by #584
