### ISSUE TITLE
Select All / None for codes by section

### ISSUE THREAD

**Issue by Auselan** [opensafely-core/opencodelists#536]
E.G. I want a list of all codes indicating an Asthma Diagnosis. I know that searching for Asthma will bring up all sorts e.g. Administrative Concepts, Assessment Scales etc.

Ideally, I want two features:
1. when adding my search term, I want to opt in or opt out of specific types of code e.g. I want to exclude Assessment Scale codes against my search
2. when I have my search results, I want to be able to 'Select NONE' against any hierarchies I didn't think to exclude e.g.
![image](https://user-images.githubusercontent.com/32044548/108726650-90e08000-751f-11eb-82e1-a086bc86b6ec.png)
box alongside Assessment Scale, so I can quickly exclude all of the codes which were found in that category of code

That would speed me up.  At present, I'm sometimes avoiding conceptualising my list in OpenSAFELY because it takes me too long to manually Exclude each of several hundred rows after I have added a keyword for the search, so I'm finding a more specific code in another database before going into OpenSAFELY e.g. |Asthma (disorder)| in order to save time.

**Comment by inglesp** [comment]
Sounds familiar... https://github.com/opensafely-core/opencodelists/issues/363

I'm afraid I have no time to work on that this week, but other users have mentioned it and I can see that it would be extremely useful.  I'll try to prioritise when I next have time to work on OpenCodelists.

**Comment by sebbacon** [comment]
Just to say as you've found a need for this twice, we'll take it as a signal it should be a priority improvement!

We have new people starting in about 4 weeks so I hope we'll be able to start accelerating development some point after that
