### ISSUE TITLE
unresolved item not visible

### ISSUE THREAD

**Issue by julianmatthewman** [opensafely-core/opencodelists#603]
I'm unable to complete a CTV3 (Read V3) codelist as the summary section tells me there is 1 unresolved item. However, clicking on unresolved doesn't show any items and I didn't find any unresolved items when manually searching the full list. The search term this happens with is "food".
![Screenshot 2021-03-25 at 14 09 05](https://user-images.githubusercontent.com/48559292/112487334-8b6f9300-8d74-11eb-973b-2d7a96290124.png)

I'm using Safari 13.1.1 and Firefox 86.0.1 on MacOS (same problem for both browsers).

**Comment by inglesp** [comment]
Hi @julianmatthewman -- can you share a link to the problem codelist?  Thanks!

**Comment by julianmatthewman** [comment]
Hi,
here it is: https://codelists.opensafely.org/builder/37001d19/
It's still a draft, as I'm not able to save it unless I resolve all items; so not sure if you will be able to see it.

**Comment by inglesp** [comment]
Hi @julianmatthewman, this is now fixed.  (And in working through the relevant code, I found a significant speedup for codelists that touch a lot of codes, like this one!)

**Comment by julianmatthewman** [comment]
Brilliant; thank you!
