### ISSUE TITLE
Toggle options to search by code/term instead of separate search buttons

### ISSUE THREAD

**Issue by HelenCEBM** [opensafely-core/opencodelists#661]
![image](https://user-images.githubusercontent.com/24392156/115378492-83b2db00-a1c8-11eb-9d87-b7091df08613.png)

Currently if you type something and press `return` it seems to default to `search by code` hence returning no results for term searches. Might be more user friendly to select search option by a toggle and then have a single `search` button.

**Comment by rebkwok** [comment]
Fixed by #671
