### ISSUE TITLE
Allow users to change codelist name or owner

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/opencodelists#678]
We want to allow users to rename a codelist or move it to another owner.  At the moment, we just need to consider changing ownership from an individual user to an organisation that they are a member of.

When making this kind of change, old URLs should redirect.  (And this will allow us to remove the hard-coded redirects from `urls.py`)

### Implementation notes

* Add new model `Handle`, with `name`, `slug`, `organisation`, `user` fields copied from `Codelist`, with a foreign key to `Codelist` and a boolean `is_current` field
* Add data migration to create relevant `Handle` models
* Remove fields that are now on `Handle` from `Codelist`
* Add `name`, `slug`, `organisation`, `user` properties to `Codelist`
* Update `create_codelist` and `create_codelist_*` actions to create `Handle` instances (inside a transaction)
* Update `update_codelist` action to take a `owner`, `name` (and maybe `slug`?) parameters, and to create a new `Handle` if required
* Update `CodelistUpdateForm` to add `owner`, `name` (and maybe `slug`) fields
  * See `owner_choices` in `opencodelists.forms.CodelistCreateForm` for inspiration
* Update `load_codelist` and `load_version` decorators to redirect to current handle
* Create `Handle` objects for redirects that are hard-coded in `urls.py`

**Comment by sebbacon** [comment]
Just to note that when we're thinking about organisation membership, we should do so with an eye to unifying one day with the work @ghickman is doing.  Sorry if repeating myself - pretty sure this has been discussed before!

For example, the permission to change owner or set organisation could be looked up on the new API. At some point.
