### ISSUE TITLE
Not opening sublists

### ISSUE THREAD

**Issue by Protocols-For-Research** [opensafely-core/opencodelists#710]
HI there,

I'm having a few bits of bother making lists.

Trying to make a list of oral steroids - 

https://codelists.opensafely.org/builder/37aa95b1/

But when I click on the little plus symbol in a box to open the sublists to inspect the 'children'  it doesn't open, or at least only opens sometimes. 

It seems if I refresh the page after clicking, it sometimes opens it...

I think it sometimes opens it but slowly. 

Closing the lists is the same...

Thanks for your help,

Joe
:)

**Comment by inglesp** [comment]
I can reproduce this.  It's likely to be related to the fix for #704, so have reverted #707.  Please re-open this if you still have problem.
