### ISSUE TITLE
Server 500 when publishing new version of a codelist

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#752]
@HelenCEBM  has tweaked this codelist to include an `inactive situation`. When I publish version it returns a server 500 error

https://www.opencodelists.org/codelist/opensafely/covid-19-vaccination-first-dose-not-given/786c94c1/

**Comment by brianmackenna** [comment]
eh I have just retried and it has worked - closing unless you want to investigate further @inglesp

**Comment by inglesp** [comment]
Definitely worth spending ten minutes understanding

**Comment by inglesp** [comment]
According to Sentry, the database was locked around the time this happened.  This happens occasionally, and should be resolved by some upcoming backend changes.
