### ISSUE TITLE
Can't find K92.2 in ICD10 builder

### ISSUE THREAD

**Issue by brianmackenna** [opensafely-core/opencodelists#765]
In this codelist I can't identify https://icd.who.int/browse10/2016/en#/K92.2

I have tried searched by code and name (without comma). Adding in comma to the name now returns a server error....poss because it detecting as same search?

**Comment by inglesp** [comment]
You need to search for `code:k922`.  See https://www.opencodelists.org/builder/001cc65e/.

Not sure what the error was.  Let me know if you see it again.
