### ISSUE TITLE
Limit Incoming Traffic

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/opencodelists#864]
[There are many instances of Django rejecting incoming traffic](https://sentry.io/organizations/ebm-datalab/issues/?project=5248013&query=is%3Aunresolved+logger%3Adjango.security.DisallowedHost&statsPeriod=14d) based on domain used to access the site.  It's likely codelists has become the default vhost in the nginx config, we should stop that traffic hitting the site.

**Comment by lucyb** [comment]
We've tested this by `curl`ing the dokku3 IP address directly with a custom host header and can confirm this is no longer the case.

To recreate

```
// 410 Gone...
curl -I --header 'Host: example.com' $ipAddress

// 310 Moved permanently...
curl -I --header 'Host: www.opencodelists.org' $ipAddress
```
