### ISSUE TITLE
Handle.DoesNotExist

### ISSUE THREAD

**Issue by ghickman** [opensafely-core/opencodelists#867]
[Sentry1](https://sentry.io/organizations/ebm-datalab/issues/2503446649/?project=5248013&query=is%3Aunresolved)

[Sentry2](https://sentry.io/organizations/ebm-datalab/issues/2502181784/?project=5248013&query=is%3Aunresolved)

**Comment by rebkwok** [comment]
Pretty sure this is the same issue as #922
